#ifndef DIALOGBOX_H
#define DIALOGBOX_H

struct record {
     int rank;
     wxString name;
     wxString nationality;
     int score;
     wxString opponent;
     int year;
};

class dialogBox: public wxDialog{
    public:
        dialogBox(const wxString& title, const wxPoint& pos, const wxSize& size);
        wxSpinCtrl* rankSpinBox;
        wxTextCtrl* nameTextBox;
        wxComboBox* nationalityComboBox;
        wxSpinCtrl* scoreSpinBox;
        wxComboBox* opponentComboBox;
        wxSpinCtrl* yearSpinBox;
};

dialogBox::dialogBox (const wxString& title, const wxPoint& pos, const wxSize& size): wxDialog((wxDialog *)NULL, -1, title, pos, size){
    wxPanel *panel = new wxPanel(this, -1);
    wxStaticText *rankLabel = new wxStaticText(panel, wxID_ANY, "Rank", wxPoint(25, 30));
    wxStaticText *nameLabel = new wxStaticText(panel, wxID_ANY, "Name", wxPoint(25, 75) );
    wxStaticText *nationalityLabel = new wxStaticText(panel, wxID_ANY, "Nationality", wxPoint(25, 120) );
    wxStaticText *scoreLabel = new wxStaticText(panel, wxID_ANY, "Score", wxPoint(25, 165) );
    wxStaticText *opponentLabel = new wxStaticText(panel, wxID_ANY, "Opponent", wxPoint(25, 210) );
    wxStaticText *yearLabel = new wxStaticText(panel, wxID_ANY, "Year", wxPoint(25, 255) );

    rankSpinBox = new wxSpinCtrl(panel, -1, "50", wxPoint(65, 25), wxSize(70, -1), wxSP_ARROW_KEYS, 1, 200, 1);
    nameTextBox = new wxTextCtrl(panel, wxID_ANY, "Enter Name", wxPoint(70, 70), wxSize(220, -1) );
    wxArrayString countries;
        countries.Add("Afghanistan");
        countries.Add("Albania");
        countries.Add("Algeria");
        countries.Add("Andorra");
        countries.Add("Angola");
        countries.Add("Antigua and Barbuda");
        countries.Add("Argentina");
        countries.Add("Armenia");
        countries.Add("Australia");
        countries.Add("Austria");
        countries.Add("Azerbaijan");
        countries.Add("The Bahamas");
        countries.Add("Bahrain");
        countries.Add("Bangladesh");
        countries.Add("Barbados");
        countries.Add("Belarus");
        countries.Add("Belgium");
        countries.Add("Belize");
        countries.Add("Benin");
        countries.Add("Bhutan");
        countries.Add("Bolivia");
        countries.Add("Bosnia and Herzegovina");
        countries.Add("Botswana");
        countries.Add("Brazil");
        countries.Add("Brunei");
        countries.Add("Bulgaria");
        countries.Add("Burkina Faso");
        countries.Add("Burundi");
        countries.Add("Cambodia");
        countries.Add("Cameroon");
        countries.Add("Canada");
        countries.Add("Cape Verde");
        countries.Add("Central African Republic");
        countries.Add("Chad");
        countries.Add("Chile");
        countries.Add("China");
        countries.Add("Colombia");
        countries.Add("Comoros");
        countries.Add("Congo, Republic of the");
        countries.Add("Congo, Democratic Republic of the");
        countries.Add("Costa Rica");
        countries.Add("Cote d'Ivoire");
        countries.Add("Croatia");
        countries.Add("Cuba");
        countries.Add("Cyprus");
        countries.Add("Czech Republic");
        countries.Add("Denmark");
        countries.Add("Djibouti");
        countries.Add("Dominica");
        countries.Add("Dominican Republic");
        countries.Add("East Timor (Timor-Leste)");
        countries.Add("Ecuador");
        countries.Add("Egypt");
        countries.Add("El Salvador");
        countries.Add("Equatorial Guinea");
        countries.Add("Eritrea");
        countries.Add("Estonia");
        countries.Add("Ethiopia");
        countries.Add("Fiji");
        countries.Add("Finland");
        countries.Add("France");
        countries.Add("Gabon");
        countries.Add("The Gambia");
        countries.Add("Georgia");
        countries.Add("Germany");
        countries.Add("Ghana");
        countries.Add("Greece");
        countries.Add("Grenada");
        countries.Add("Guatemala");
        countries.Add("Guinea");
        countries.Add("Guinea-Bissau");
        countries.Add("Guyana");
        countries.Add("Haiti");
        countries.Add("Honduras");
        countries.Add("Hungary");
        countries.Add("Iceland");
        countries.Add("India");
        countries.Add("Indonesia");
        countries.Add("Iran");
        countries.Add("Iraq");
        countries.Add("Ireland");
        countries.Add("Israel");
        countries.Add("Italy");
        countries.Add("Jamaica");
        countries.Add("Japan");
        countries.Add("Jordan");
        countries.Add("Kazakhstan");
        countries.Add("Kenya");
        countries.Add("Kiribati");
        countries.Add("Korea, North");
        countries.Add("Korea, South");
        countries.Add("Kosovo");
        countries.Add("Kuwait");
        countries.Add("Kyrgyzstan");
        countries.Add("Laos");
        countries.Add("Latvia");
        countries.Add("Lebanon");
        countries.Add("Lesotho");
        countries.Add("Liberia");
        countries.Add("Libya");
        countries.Add("Liechtenstein");
        countries.Add("Lithuania");
        countries.Add("Luxembourg");
        countries.Add("Macedonia");
        countries.Add("Madagascar");
        countries.Add("Malawi");
        countries.Add("Malaysia");
        countries.Add("Maldives");
        countries.Add("Mali");
        countries.Add("Malta");
        countries.Add("Marshall Islands");
        countries.Add("Mauritania");
        countries.Add("Mauritius");
        countries.Add("Mexico");
        countries.Add("Micronesia, Federated States of");
        countries.Add("Moldova");
        countries.Add("Monaco");
        countries.Add("Mongolia");
        countries.Add("Montenegro");
        countries.Add("Morocco");
        countries.Add("Mozambique");
        countries.Add("Myanmar (Burma)");
        countries.Add("Namibia");
        countries.Add("Nauru");
        countries.Add("Nepal");
        countries.Add("Netherlands");
        countries.Add("New Zealand");
        countries.Add("Nicaragua");
        countries.Add("Niger");
        countries.Add("Nigeria");
        countries.Add("Norway");
        countries.Add("Oman");
        countries.Add("Pakistan");
        countries.Add("Palau");
        countries.Add("Panama");
        countries.Add("Papua New Guinea");
        countries.Add("Paraguay");
        countries.Add("Peru");
        countries.Add("Philippines");
        countries.Add("Poland");
        countries.Add("Portugal");
        countries.Add("Qatar");
        countries.Add("Romania");
        countries.Add("Russia");
        countries.Add("Rwanda");
        countries.Add("Saint Kitts and Nevis");
        countries.Add("Saint Lucia");
        countries.Add("Saint Vincent and the Grenadines");
        countries.Add("Samoa");
        countries.Add("San Marino");
        countries.Add("Sao Tome and Principe");
        countries.Add("Saudi Arabia");
        countries.Add("Senegal");
        countries.Add("Serbia");
        countries.Add("Seychelles");
        countries.Add("Sierra Leone");
        countries.Add("Singapore");
        countries.Add("Slovakia");
        countries.Add("Slovenia");
        countries.Add("Solomon Islands");
        countries.Add("Somalia");
        countries.Add("South Africa");
        countries.Add("South Sudan");
        countries.Add("Spain");
        countries.Add("Sri Lanka");
        countries.Add("Sudan");
        countries.Add("Suriname");
        countries.Add("Swaziland");
        countries.Add("Sweden");
        countries.Add("Switzerland");
        countries.Add("Syria");
        countries.Add("Taiwan");
        countries.Add("Tajikistan");
        countries.Add("Tanzania");
        countries.Add("Thailand");
        countries.Add("Togo");
        countries.Add("Tonga");
        countries.Add("Trinidad and Tobago");
        countries.Add("Tunisia");
        countries.Add("Turkey");
        countries.Add("Turkmenistan");
        countries.Add("Tuvalu");
        countries.Add("Uganda");
        countries.Add("Ukraine");
        countries.Add("United Arab Emirates");
        countries.Add("United Kingdom");
        countries.Add("United States of America");
        countries.Add("Uruguay");
        countries.Add("Uzbekistan");
        countries.Add("Vanuatu");
        countries.Add("Vatican City (Holy See)");
        countries.Add("Venezuela");
        countries.Add("Vietnam");
        countries.Add("Yemen");
        countries.Add("Zambia");
        countries.Add("Zimbabwe");
    nationalityComboBox = new wxComboBox(panel, -1, "Barbados", wxPoint(100, 115), wxSize(175, -1), countries, wxCB_READONLY);
    scoreSpinBox = new wxSpinCtrl(panel, -1, "0", wxPoint(65, 160), wxSize(70, -1), wxSP_ARROW_KEYS, 0, 9999, 1);
    opponentComboBox = new wxComboBox(panel, -1, "Barbados", wxPoint(95, 205), wxSize(175, -1), countries, wxCB_READONLY);
    yearSpinBox = new wxSpinCtrl(panel, -1, "2020", wxPoint(60, 250), wxSize(70, -1), wxSP_ARROW_KEYS, 1111, 3000, 1);

    wxButton* okBtn = new wxButton(panel, wxID_OK, "&OK", wxPoint(75, 300), wxDefaultSize, 0);
    wxButton* cancelBtn = new wxButton(panel, wxID_CANCEL, "&CANCEL", wxPoint(170, 300), wxDefaultSize, 0 );
    Centre();
}
#endif